name: Deploy

on:
  push:
    branches: [ live ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Write secret
        run: 'echo "$ID_RSA_DEPLOY" > ssh/id_rsa_deploy && chmod 600 ssh/id_rsa_deploy'
        env:
          ID_RSA_DEPLOY: ${{secrets.ID_RSA_DEPLOY}}
        
      - name: Deploy
        run: yarn deploy