name: Webpack build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build prod
        run: yarn build:prod

      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: prod
          path: dist/
          if-no-files-found: error
